sudo: required
services: 
        - docker

before_install:
        - docker build -f Dockerfile.dev -t docker-practice/docker-react .

script:
        - docker run docker-practice/docker-react npm run test -- --coverage
          
