sudo: required
services: 
        - docker

before_install:
        - docker build -t docker-practice/docker-react -f Dockerfile.dev .

script:
        - docker run docker-practice/docker-react npm run test -- --coverage
          
